name: blog_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.6
  firebase_core: ^2.24.2
  font_awesome_flutter: ^10.6.0
  lottie: ^2.7.0
  shared_preferences: ^2.2.2
  firebase_auth: ^4.15.3
  google_sign_in: ^6.2.1
  fluttertoast: ^8.2.4
  cloud_firestore: ^4.13.6
  http: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
